# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
github:
  zip_url: null

repository: kirek007/braindump
title: Braindump
email: kirek007 [plus] blog [at] gmail [dot] com
description: >- # this means to ignore newlines until "baseurl:"
    Sharing is caring.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.kir.ovh # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kirek007
github_username: kirek007
theme: minima
# Build settings
markdown: kramdown

#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
